### ISSUE TITLE
Full support for Bioc-devel packages

### ISSUE THREAD

**Issue by lcolladotor** [metacran/r-builder#11]
Hi,

Bioconductor software packages are built on a nightly basis. They are then made available via the usual installation procedure (shown below) if the latest version succeeds. 

```R
source("http://bioconductor.org/biocLite.R")
biocLite("SomeBioCPackage")
```

This means that in some cases you cannot test your package because package `X` needs package `Y` which has not been made available yet. For example, right now (2014/11/04 at 2 am US ET) some packages require `GenomicRanges` 1.19.3 with `biocLite('GenomicRanges')` installing version 1.19.2 The most updated version of `GenomicRanges` is 1.19.4 and is only available via SVN. There is more information about Bioconductor's svn repositories at http://www.bioconductor.org/developers/how-to/source-control/ In particular, you can use the following to download the latest `GenomicRanges` package:

```bash
## Bioc-devel version of GenomicRanges
svn co https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/GenomicRanges --username readonly
```

Then, it's a matter of installing locally.

For Bioconductor developers it could be useful to use the latest versions while testing with Travis. You could argue that all of this is a minor issue as you can simply wait a couple of hours/days for the necessary versions to be available via `biocLite()`.

--------------

For BioC-release, this scenario is much less frequent as Bioconductor package developers are encouraged to only commit bug fixes to the release branch. However, if you really wanted to download  the BioC-release packages via svn you can do so as explained in http://www.bioconductor.org/developers/how-to/source-control/

In any case, I am much more interested in using svn versions of the packages for BioC-devel. 

--------

Thoughts @PeteHaitch @siddharthab?

**Comment by richierocks** [comment]
Does `install_github Bioconductor-mirror/pkgname` work? 

That is, for SemaphoreCI, in the test script for each thread, add the line 

```
./pkg-build.sh install_github Bioconductor-mirror/pkgname
```

For Travis CI, in the `.travis.yml`:

```
install:
  - ./pkg-build.sh install_github Bioconductor-mirror/pkgname
```

**Comment by lcolladotor** [comment]
Yes, that should work. At the time I wrote this issue `Bioconductor-mirror` did not exist.

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.

**Comment by lcolladotor** [comment]
Thanks @gaborcsardi, `r-builder` was very useful before R was added to Travis (and likely still is for some use cases). I saw your same message for several `r-builder` issues and just wanted to thank you for the work you put into `r-builder`!
