### ISSUE TITLE
CircleCI support

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/r-builder#15]
Now that they are free.

**Comment by jsonbecker** [comment]
FWIW I am running my builds in CircleCI (in a docker container) fine, but the one limitation is that `testthat` messages appear to not to be read properly by Circle. Test failures aren't sent to stderr and I am only able to see whatever messages are sent, not actually get color coding or true failures or successes on the R package portion.

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
