### ISSUE TITLE
Try Docker-based Travis

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/r-builder#20]
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by gaborcsardi** [comment]
It works, but it is actually not any faster, because
- there is no apt caching
- it is difficult to cache the R installation

**Comment by sahilseth** [comment]
If caching of packages can be enabled, it can lead to much faster processing. For example a package I have used to take [11 minutes](https://travis-ci.org/sahilseth/flowr/builds/81409006) and now takes about [2min](https://travis-ci.org/sahilseth/flowr/builds/81474818). 

This makes a huge difference if you have a lot of dependencies, else it may not make a significant difference.

A few lines instrumental in achieving this are:

```
# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib

install:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")' ## update all packages !
```

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
