### ISSUE TITLE
Should this be an R package instead?

### ISSUE THREAD

**Issue by krlmlr** [metacran/r-builder#25]
Now that Travis has (kind of) built-in support for R.

**Comment by gaborcsardi** [comment]
Could be, I guess. But what's the plus? It would be an R package that only runs on Travis?

**Comment by krlmlr** [comment]
It can run on Travis, on other CIs and *locally*, providing uniform workflow.

**Comment by gaborcsardi** [comment]
Hmmm, that sounds quite good, actually.

**Comment by gaborcsardi** [comment]
But it also seems to be a lot of work, especially to support various local environments.

**Comment by krlmlr** [comment]
I'd leave that to the CI system. The job of this package would be to orchestrate "best practices", perhaps via a config file.

Are you going to useR! ?

**Comment by gaborcsardi** [comment]
Hmmm, I don't know. The job so far was simply to do CI for R packages. :) 

Yes, I am going to Denmark.

**Comment by krlmlr** [comment]
"best practices" = for CI -- building, testing, coverage, linting, and then running roxygen, building staticdocs, and whatever the future brings. I see some overlap with r-builder, but I agree it's not entirely the same.

Also, this might be something `devtools` might support as well. Probably easier to start with a dedicated package and to merge later if necessary.

**Comment by gaborcsardi** [comment]
Hmmm, interesting. Also, very ambitious. :) I like it, but I probably won't be able to work on it for a while.

I don't think this could go into devtools. They are actually thinking about break it up, because it is too big already.

**Comment by krlmlr** [comment]
Thanks for letting me know. Let's keep that idea in mind.

**Comment by lcolladotor** [comment]
Very ambitious indeed. I'll just keep an eye open =)

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
