### ISSUE TITLE
R-builder should not set environment variable CI

### ISSUE THREAD

**Issue by jimhester** [metacran/r-builder#29]
i.e. https://travis-ci.org/gaborcsardi/argufy/jobs/76117641#L1986-L1987

This variable is used as part of codecov's CI detection (in covr https://github.com/jimhester/covr/blob/master/R/codecov.R#L50-L60, python implementation https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L230-L240)

Both implementations are expecting `CI` to simply be `true` if running within a CI and unset otherwise, so R-builder setting it to the CI name breaks the detection, which is why covr and codecov do not work using r-builder.

It looks like changing this would either require renaming the variable r-builder sets or a rewrite of some of the logic, I can send a pull request for the former if you decide that is best.

This is the cause of https://github.com/jimhester/covr/issues/107

**Comment by gaborcsardi** [comment]
Thanks for investigating this! Sure, we can rename the variable, no problem, I think.

**Comment by jimhester** [comment]
Closed by https://github.com/metacran/r-builder/pull/30
