### ISSUE TITLE
Install Suggests in Addition to Depends

### ISSUE THREAD

**Issue by bleutner** [metacran/r-builder#31]
Hi, 

I had an issue with missing *Suggests* packages. Some of my examples require suggested packages to run. 
In my opinion it would make sense to install *Suggests* along with *Depends* automatically.

This is how I adapted the InsatllDeps()

    InstallDeps() {
        EnsureDevtools
        Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="'"${CRAN}"'"));    update(dev_package_deps(dependencies = c("Depends", "Imports", "Suggests", "LinkingTo")))'
    }

Cheers
Benjamin

**Comment by gaborcsardi** [comment]
Currently we have this: https://github.com/metacran/r-builder/blob/6379758d1014afcbc7ab313613152cfd76b247a5/pkg-build.sh#L243
and `dependencies` is just passed to `install.packages`, for which we have:

          ‘TRUE’ means to use ‘c("Depends", "Imports", "LinkingTo",
          "Suggests")’ for ‘pkgs’ and ‘c("Depends", "Imports",
          "LinkingTo")’ for added dependencies: this installs all the
          packages needed to run ‘pkgs’, their examples, tests and
          vignettes (if the package author specified them correctly).

So by default the suggested packages are installed, too, at least for the package you are checking. Can you show me an example r-builder run when this did not work?

**Comment by bleutner** [comment]
sorry, I did not read the full log and jumped to the wrong conclusion prematurely. You are right, it was installing the Suggests automatically and the only the problem was that one suggested package failed to install and hence was not available in the checks.

Something else: I needed an old version of a particular package and added a function to pkg-build.sh to install specific versions of packages. Would this be of interest? If so I'll create a pull request.

**Comment by gaborcsardi** [comment]
Yes, that would be useful. Thanks.
