### ISSUE TITLE
Support rscript in post-build event

### ISSUE THREAD

**Issue by renkun-ken** [metacran/r-builder#36]
I was using https://github.com/craigcitro/r-travis version of travis+R. In `.travis.yml` a post-build script should be executed:

```
after_success:
  - Rscript -e 'library(covr);coveralls()'
```

It works correctly with https://github.com/craigcitro/r-travis, but it does not seem to work with https://github.com/metacran/r-builder, and a message in travis-ci shows

```
$ Rscript -e 'library(covr);coveralls()'
/home/travis/build.sh: line 41: Rscript: command not found
```

**Comment by gaborcsardi** [comment]
See https://github.com/metacran/r-builder/issues/28#issuecomment-135415303

**Comment by renkun-ken** [comment]
Thanks, but https://github.com/metacran/r-builder/blob/master/pkg-build.sh#L301 does not seem to support the command line like 

```
Rscript -e 'covr::coveralls()'
```

since `RunScript()` forces the argument to be enclosed with quotation marks.

**Comment by gaborcsardi** [comment]
It does support that. See e.g. https://github.com/gaborcsardi/argufy/blob/master/.travis.yml#L23

**Comment by renkun-ken** [comment]
Thanks a lot for your example!
