### ISSUE TITLE
make --as-cran flag optional

### ISSUE THREAD

**Issue by goldingn** [metacran/r-builder#37]
It would be great if checking with the `--as-cran` flag could be made optional. This would be helpful for projects that either aren't aimed at CRAN, or which have additional tests that `check --as-cran` can't handle.

E.g. I have a fork which does this using a `NOT_CRAN` environment variable (the same variable is used in `testthat::skip_on_cran()`), but keeping the default behaviour the same: https://github.com/goldingn/r-builder/commit/8b5df1b095eba5b2f1f57c16a8b19c751452ea01. I'm sure there's a neater approach though.

**Comment by gaborcsardi** [comment]
You can set the `R_CHECK_ARGS` environment variable with the options you want. https://github.com/metacran/r-builder/blob/master/pkg-build.sh#L58

**Comment by goldingn** [comment]
Ah, sorry about that. Completely misunderstood the code and thought extra options were being appended to those.
