### ISSUE TITLE
Build failure on Semaphore: R version 3.2.2

### ISSUE THREAD

**Issue by MattMSumner** [metacran/r-builder#38]
I'm getting the following error on semaphore when running `./pkg-build.sh install_deps`:
```
Running command: install_deps
+ shift
+ case $COMMAND in
+ InstallDeps
+ EnsureDevtools
+ Rscript -e 'if (!("devtools" %in% rownames(installed.packages()))) q(status=1)'
+ Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="http://cran.rstudio.com")); install_deps(dependencies = TRUE)'
Error in if (create) { : missing value where TRUE/FALSE needed
Calls: install_deps ... dev_package_deps -> as.package -> load_pkg_description
Execution halted
```

Any thoughts on how I can move forward?

My semaphore build setup is thus:

![screen shot 2015-11-03 at 1 38 57 pm](https://cloud.githubusercontent.com/assets/759721/10917762/71c1c20c-8230-11e5-9fe4-ac9f5a32ee5d.png)

**Comment by gaborcsardi** [comment]
Can you point me to your repo and the full build log? Assuming it is public....

**Comment by MattMSumner** [comment]
Unfortunately it's not public. I actually moved forward by installing `R` via `apt-get`.

Later tonight I can try on a fresh build to see what's up.

**Comment by gaborcsardi** [comment]
Closing this now, please reopen if you have issues.
