### ISSUE TITLE
This R version is not available for this CI

### ISSUE THREAD

**Issue by sckott** [metacran/r-builder#39]
Getting that error on some builds, usually oldrel and release

e.g, https://travis-ci.org/ropensci/binomen/jobs/88548186#L146

**Comment by gaborcsardi** [comment]
The web service that mapped release and oldrel to version was down. Should be OK now.

**Comment by gaborcsardi** [comment]
Sorry about it! I'll make these services redundant, now with r-hub.

**Comment by sckott** [comment]
:+1:

**Comment by gaborcsardi** [comment]
Closing this now.

**Comment by bbolker** [comment]
I'm getting this now for r-release ... https://travis-ci.org/glmmTMB/glmmTMB/jobs/237010744

**Comment by gaborcsardi** [comment]
@bbolker I cannot build r-release for the this old Ubuntu version: https://travis-ci.org/metacran/r-builder/

Please consider using the new community supported Docker-based R-travis.

**Comment by bbolker** [comment]
Hmm.  Can you point me to a starting point for docs?  I've poked around for 15 mins (can post links if you like) but can't find anything sufficiently useful to get me started.  I tried setting `os: linux; dist: trusty`, but that didn't seem to help.  I have `sudo:required` set, maybe I should try to go to `sudo:false`?  I'll check and see if there's a new `travis.yml` template I can start from ...

**Comment by gaborcsardi** [comment]
https://docs.travis-ci.com/user/languages/r/

**Comment by bbolker** [comment]
Thank you!
