### ISSUE TITLE
Describe how to build against multiple versions of R

### ISSUE THREAD

**Issue by richierocks** [metacran/r-builder#40]
The README quite rightly recommends that

> you test your package with R-devel, R-release and R-oldrel.

Please document how you can set this up.

For Semaphore, I'm guessing you have thread commands like:

```
./pkg-build.sh bootstrap
./pkg-build.sh install_deps
RVERSION=devel
./pkg-build.sh run_tests
RVERSION=release
./pkg-build.sh run_tests
RVERSION=oldrel
./pkg-build.sh run_tests
```

(untested)

**Comment by gaborcsardi** [comment]
Good idea!

I guess for Semaphore you need to re-run bootstrap and install_deps as well.

For Travis you have matrix builds, so it is easy:
https://github.com/metacran/r-builder/blob/b450cb7ce04771fcb6e094ed2f9f36bdb50b6007/sample.travis.yml#L26-L30

**Comment by richierocks** [comment]
I just tried this with

```
RVERSION=devel
./pkg-build.sh bootstrap
./pkg-build.sh install_deps
./pkg-build.sh run_tests
```

on one thread and 


```
RVERSION=release
./pkg-build.sh bootstrap
./pkg-build.sh install_deps
./pkg-build.sh run_tests
```

on another.

Unfortunately in the `bootstrap` section, I'm getting the message

> RVERSION environment variable is not set, will use R-devel

Am I doing somethign stupid?

**Comment by gaborcsardi** [comment]
Don't you just need `export RVERSION=...` ?

**Comment by richierocks** [comment]
OK, yes, that works.  I just spotted a couple of other doc fixes for the README.

The line

> ./pkg-build install_github repo1/pkg1 repo2/pkg2 ... etc

should be

> ./pkg-build.sh install_github repo1/pkg1 repo2/pkg2 ... etc

I think,and I don't think

> Use the Ubuntu 14.04 LTS v1410.1 platform.

is an option anymore; the [documentation](https://semaphoreci.com/docs/supported-stack.html) suggests that all builds are on Ubuntu 14.04 LTS 64-bit, so this line can be cut.

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
