### ISSUE TITLE
How to include dependencies in private repos?

### ISSUE THREAD

**Issue by richierocks** [metacran/r-builder#41]
Using Semaphore + Bitbuckeet, I tried to get a private dependency using

    ./pkg-build.sh install_bitbucket user/private_repo

This didn't work.  How can I pass the `auth_user` and `password` arguments to `install_bitbucket`?

(For bonus points, how do I not give my password in plain text?)

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
