### ISSUE TITLE
Question: how to run "covr::codecov()" after success?

### ISSUE THREAD

**Issue by jotsetung** [metacran/r-builder#45]
First of all: tremendous work! Find it very useful!
However, I did not find a way yet to run covr's codecov function after sucessful test. How can I do that? I've added a:

```
after_success:
  - ./pkg-build.sh r_script -e 'covr::codecov()'

```
But that does not seem to work...

**Comment by gaborcsardi** [comment]
Here is a complete example with `codecov` and multiple R versions:
https://github.com/MangoTheCat/simplegraph/blob/master/.travis.yml

You probably only want to run `covr` once, on r-devel or r-release, whichever you prefer.

**Comment by jotsetung** [comment]
Great! Thanks!
