### ISSUE TITLE
Failure to install packages

### ISSUE THREAD

**Issue by AugustT** [metacran/r-builder#46]
We use r-builder for testing our packages on Travis. We note that since r-builder has been having build failures our packages also fail to build (previously there were no issues) with the following error:

`
+Rscript -e 'install.packages(commandArgs(TRUE), repos="http://cran.rstudio.com")' testthat curl
Warning: unable to access index for repository http://cran.rstudio.com/src/contrib:
  internet routines cannot be loaded
`
[linked here](https://travis-ci.org/zoonproject/zoon/jobs/120840401#L513)

I suspect our issues are linked to your issues:

`configure: error: libcurl >= 7.28.0 library and headers are required with support for https`

[linked here](https://travis-ci.org/zoonproject/zoon/jobs/120840401#L513)

Do you have any insights, or perhaps you are working on a fix?

Our issues: https://github.com/zoonproject/zoon/pull/256#partial-pull-merging

**Comment by gaborcsardi** [comment]
Thanks for the feedback! 

On the longer run, I suggest that you switch to proper R Travis. Travis has very nice built-in R support now, supporting multiple versions. See http://blog.rstudio.org/2016/03/09/r-on-travis-ci/

Nevertheless, I'll look at the error, and will fix it asap, probably tomorrow.

**Comment by AugustT** [comment]
Thanks for the pointers. We will have a look into the new R support and see if that would work for us.

**Comment by gaborcsardi** [comment]
I think it should be all good now. I am sorry it took so long. If you still have problems, please reopen this issue. Thanks!

**Comment by AugustT** [comment]
Thanks @gaborcsardi !
