### ISSUE TITLE
Add support for BiocCheck

### ISSUE THREAD

**Issue by richierocks** [metacran/r-builder#47]
For checking packages to be submitted to Bioconductor, as well as R CMD check, you also need to run R CMD BiocCheck. See:

https://www.bioconductor.org/packages/release/bioc/html/BiocCheck.html

The [Vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html) gives the setup and usage details.

It would be great if `pkg-build.sh` supported running BiocCheck.  (Since most of the checks aren't Bioconductor-specific, this is pretty useful even if you only develop for CRAN.)

**Comment by gaborcsardi** [comment]
I think you can do this via `./pkg_build.sh run_script -e ...`

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
