### ISSUE TITLE
Create binaries of the packages that are always needed

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/r-builder#6]
These are currently installed from CRAN: devtools, testthat, etc.

The difficulty is that we need to know when to rebuild them. Also, a new version on CRAN might not work with an older R version. 

So this might be a bad ideally, actually.

**Comment by HenrikBengtsson** [comment]
Would it be possible for `EnsureDevtools()` to:

1. Install all \<devtools et al\> packages explicitly via `AptGetInstall()`
2. Then check for updates on CRAN; think `update.packages("<devtools et al>")`.

If there are no updates, the 2nd step should be quick.  If there are updates, it's unlikely all packages will be updated, so together Step 1 + Step 2 should speed things up.

**Comment by gaborcsardi** [comment]
@HenrikBengtsson That's also an option. What I originally had in mind was including these packages in the binary build. But this is not a priority for me now, actually.

**Comment by HenrikBengtsson** [comment]
I'd say anything that minimize redundancy and maintenance.  Then there's also the Docker path and I'm sure someone somewhere is already providing related containers.  Just some thoughts.

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
