### ISSUE TITLE
OSX support on Travis

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/r-builder#7]
Should not be difficult, I guess.

**Comment by achubaty** [comment]
Doesn't need a separate branch. See https://ropensci.org/blog/2016/07/12/travis-osx

I've recently been using a build matrix to do builds on all 3 R versions on precise, R release on trusty, and R release on OSX. It's working great.

**Comment by gaborcsardi** [comment]
> Doesn't need a separate branch.

Any more. It used to.

r-builder is deprecated. Don't use it, use the proper Travis support for R.

**Comment by achubaty** [comment]
thanks for the update re: r-builder
